name: resbook
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  modal_progress_hud_nsn: ^0.3.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  provider: ^6.0.5
  js: ^0.6.2
  firebase_storage: ^11.0.10
  image_picker: ^0.8.6+1
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

